version: "3.8"

services:
  api:
    build: .
    container_name: wanted_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    environment:
      - PYTHONPATH=/code
    env_file:
      - .env
    restart: on-failure
    networks:
      - shared_net

networks:
  shared_net:
    name: shared_net
    external: true
